default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  database: <%= ENV['DATABASE_URL'] %> # Optionally, you can use an env variable for the database URL.
  
development:
  <<: *default
  database: collaborative_calendar_backend_development
  username: pato
  password: admin
  host: localhost

test:
  <<: *default
  database: collaborative_calendar_backend_test
  username: pato
  password: admin
  host: localhost

production:
  <<: *default
  database: collaborative_calendar_backend_production
  username: pato
  password: <%= ENV['COLLABORATIVE_CALENDAR_BACKEND_DATABASE_PASSWORD'] %>
  host: localhost
